apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: broker-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: broker-deployment
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - sh
            - -c
            - sleep 1h          
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
      restartPolicy: Always
      securityContext:
        runAsUser: 30000
        # The allowPrivilegeEscalation is not available in the PodSpec object