apiVersion: apps/v1
kind: Deployment
# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
metadata:
  name: broker-deployment
spec:
  progressDeadlineSeconds: 600
  # The maximum time in seconds for a deployment to make progress before it is considered to be failed.
  # The deployment controller will continue to process failed deployments and a condition
  # with a ProgressDeadlineExceeded reason will be surfaced in the deployment status.
  # Note that progress will not be estimated during the time a deployment is paused. Defaults to 600s.
  replicas: 1
  revisionHistoryLimit: 10
  # The number of old ReplicaSets to retain to allow rollback.
  # This is a pointer to distinguish between explicit zero and not specified. Defaults to 10.
  selector:
    matchLabels:
      app: broker-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: broker-deployment
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - sh
            - -c
            - sleep 1h          
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
      restartPolicy: Always
      securityContext:
        runAsUser: 30000
        # The allowPrivilegeEscalation is not available in the PodSpec object
