# https://github.com/dgkanatsios/CKAD-exercises/blob/main/b.multi_container_pods.md
# Create a pod with an nginx container exposed on port 80.
# Add a busybox init container which downloads a page using 'echo "Test" > /work-dir/index.html'.
# Make a volume of type emptyDir and mount it in both containers.
# For the nginx container, mount it on "/usr/share/nginx/html" and for the initcontainer, mount it on "/work-dir".
# When done, get the IP of the created pod and create a busybox pod and run "wget -O- IP"
# k run nginx --image=nginx --port=80 --dry-run=client -o yaml > pod.yaml
# k describe po nginx

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  initContainers:
  - name: init
    image: busybox
    args:
      - /bin/sh
      - "-c"
      - 'echo "Test" > /work-dir/index.html'
    volumeMounts:
      - name: default
        mountPath: /work-dir
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
      - name: default
        mountPath: /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: default
      emptyDir: {}
status: {}

# k get po nginx -o wide
# -o wide 是常用參數，要記住
# k run busybox2 --image=busybox -it --rm --restart=Never -- /bin/sh -c "wget -O- 10.244.1.14:80"
# 「wget -O-」格式是正確的
#  要加 --restart=Never 不然啟動時就會卡住
