apiVersion: apps/v1
kind: Deployment
metadata:
  name: nosql
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          requests:
            cpu: 30m
            memory: 35Mi
        ports:
        - containerPort: 80