# https://github.com/dgkanatsios/CKAD-exercises/blob/main/g.state.md
# Create a PersistentVolume of 10Gi, called 'myvolume'.
# Make it have accessMode of 'ReadWriteOnce' and 'ReadWriteMany',
# storageClassName 'normal', mounted on hostPath '/etc/foo'.
# Save it on pv.yaml, add it to the cluster.
# Show the PersistentVolumes that exist on the cluster

# IMPORTANT 要多練習的地方
# https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1/#PersistentVolumeSpec

# 使用者可以在 minikube 建立叢集時，運用 minikube 的 --mount 參數指定掛載本地目錄，例如
# docker context use default
# minikube start --nodes=2 --mount-string "D:\kubernetes_certifications\minikube-host:/minikube-host" --mount=true
# 這樣之後就不用再額外啟動某個命令列並呼叫 minikube mount
# 使用者可以透過掛載上去的目錄提供檔案給叢集，但似乎沒辦法直接從裡面取得檔案

apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvolume
spec:
  storageClassName: normal
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: "/etc/foo"

# k get pv myvolume
# k describe pv myvolume

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: myvolume
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem
#   # A volume with volumeMode: Filesystem is mounted into Pods into a directory.
#   # If the volume is backed by a block device and the device is empty,
#   # Kubernetes creates a filesystem on the device before mounting it for the first time.
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: normal
#   hostPath:
#     path: /etc/foo
    # type: Directory
