# https://github.com/dgkanatsios/CKAD-exercises/blob/main/g.state.md
# Create a busybox pod with command 'sleep 3600', save it on pod.yaml.
# Mount the PersistentVolumeClaim to '/etc/foo'.
# Connect to the 'busybox' pod, and copy the '/etc/passwd' file to '/etc/foo/passwd'
# k run busybox --image=busybox --restart=Never --dry-run=client -o yaml -- sleep 3600 > pod.yaml
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#claims-as-volumes
# k apply -f ./practices/ckad/g.state/define_volumes-4.yaml
# k exec busybox -it -- /bin/sh

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: busybox
    resources: {}
    volumeMounts:
      - name: default
        mountPath: /etc/foo
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: default
      persistentVolumeClaim:
        claimName: mypvc
status: {}
