# https://github.com/dgkanatsios/CKAD-exercises/blob/main/g.state.md
# Create a busybox pod with command 'sleep 3600', save it on pod.yaml.
# Mount the PersistentVolumeClaim to '/etc/foo'.
# Connect to the 'busybox' pod, and copy the '/etc/passwd' file to '/etc/foo/passwd'
# k run busybox --image=busybox --restart=Never --dry-run=client -o yaml -- /bin/sh -c "sleep 3600" > pod.yaml
# IMPORTANT 不熟悉要多練的部分
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#claims-as-volumes
# k exec busybox -c busybox -it -- /bin/sh

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox
    resources: {}
    volumeMounts:
      - name: mypvc
        mountPath: /etc/foo
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: mypvc
     
status: {}

# Create a second pod which is identical with the one you just created (you can easily do it by changing the 'name' property on pod.yaml).
# Connect to it and verify that '/etc/foo' contains the 'passwd' file. Delete pods to cleanup.
# Note: If you can't see the file from the second pod, can you figure out why? What would you do to fix that?


# Create a busybox pod with 'sleep 3600' as arguments. Copy '/etc/passwd' from the pod to your local folder
