# https://github.com/dgkanatsios/CKAD-exercises/blob/main/g.state.md
# Create a PersistentVolumeClaim for this PersistentVolume, called 'mypvc', a request of 4Gi and an accessMode of ReadWriteOnce,
# with the storageClassName of normal, and save it on pvc.yaml. Create it on the cluster.
# Show the PersistentVolumeClaims of the cluster. Show the PersistentVolumes of the cluster
# 參照不是很容易找 https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: normal
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mypvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 4Gi
#   storageClassName: normal # Empty string must be explicitly set otherwise default StorageClass will be set
#   volumeName: myvolume

# k get pvc mypvc
# k describe pvc mypvc
