# https://github.com/dgkanatsios/CKAD-exercises/blob/main/g.state.md
# Create busybox pod with two containers, each one will have the image busybox and will run the 'sleep 3600' command.
# Make both containers mount an emptyDir at '/etc/foo'. Connect to the second busybox, write the first column of '/etc/passwd' file to '/etc/foo/passwd'.
# Connect to the first busybox and write '/etc/foo/passwd' file to standard output. Delete pod.
# k run busybox --image=busybox --restart=Never -o yaml --dry-run=client -- /bin/sh -c "sleep 3600" > pod.yaml
# k exec busybox -c busybox2 -it -- /bin/sh
# k exec busybox -c busybox1 -it -- /bin/sh
# k delete po busybox

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox
    resources: {}
    volumeMounts:
      - name: foo
        mountPath: /etc/foo
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox2
    resources: {}
    volumeMounts:
      - name: foo
        mountPath: /etc/foo
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: foo
      emptyDir: {}
status: {}

# Create a PersistentVolume of 10Gi, called 'myvolume'. Make it have accessMode of 'ReadWriteOnce' and 'ReadWriteMany',
# storageClassName 'normal', mounted on hostPath '/etc/foo'. Save it on pv.yaml, add it to the cluster.
# Show the PersistentVolumes that exist on the cluster

# Create a PersistentVolumeClaim for this PersistentVolume, called 'mypvc', a request of 4Gi and an accessMode of ReadWriteOnce,
# with the storageClassName of normal, and save it on pvc.yaml. Create it on the cluster.
# Show the PersistentVolumeClaims of the cluster. Show the PersistentVolumes of the cluster

# Create a busybox pod with command 'sleep 3600', save it on pod.yaml.
# Mount the PersistentVolumeClaim to '/etc/foo'.
# Connect to the 'busybox' pod, and copy the '/etc/passwd' file to '/etc/foo/passwd'

# Create a second pod which is identical with the one you just created (you can easily do it by changing the 'name' property on pod.yaml).
# Connect to it and verify that '/etc/foo' contains the 'passwd' file. Delete pods to cleanup.
# Note: If you can't see the file from the second pod, can you figure out why? What would you do to fix that?

# Create a busybox pod with 'sleep 3600' as arguments. Copy '/etc/passwd' from the pod to your local folder
