apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  # 參考解答自訂的
  storageClassName: keys
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi