apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    ports:
    - containerPort: 80
    command: [ "env" ]

# 或是
# kbl run nginx -n mynamespace --image=nginx --restart=Never

# k run busybox --image=busybox --restart=Never -- env
# 也可以加上 -it 和 --rm 選項
