# https://github.com/dgkanatsios/CKAD-exercises/blob/main/a.core_concepts.md
# Create a busybox pod (using kubectl command) that runs the command "env". Run it and see the output
# k run busybox --image=busybox --restart=Never -it -- env

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - env
    image: busybox
    name: busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

# Create a busybox pod (using YAML) that runs the command "env". Run it and see the output
# k apply -f ./practices/ckad/a.core_concepts/3-4.yaml
