# https://github.com/dgkanatsios/CKAD-exercises/blob/main/a.core_concepts.md
# Get the YAML for a new namespace called 'myns' without creating it
# k create ns myns --dry-run=client -o yaml > ns.yaml

apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: myns
spec: {}
status: {}
