# https://github.com/dgkanatsios/CKAD-exercises/blob/main/a.core_concepts.md
# Create the YAML for a new ResourceQuota called 'myrq' with hard limits of 1 CPU, 1G memory and 2 pods without creating it
# kubectl create quota myrq --hard=cpu=1,memory=1G,pods=2 --dry-run=client -o yaml

apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: myrq
spec:
  hard:
    cpu: "1"
    memory: 1G
    pods: "2"
status: {}

# k apply -f ./practices/ckad/a.core_concepts/6.yaml
# k describe quota myrq
