apiVersion: v1
kind: Pod
metadata:
  name: nginx-resources
spec:
  containers:
  - name: nginx
    image: nginx:1.16
    resources:
      requests:
        cpu: 40m
        memory: 50Mi
    ports:
    - containerPort: 80