apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: keys
  fc:
    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#fcvolumesource-v1-core
    hostPath: 
      path: /opt/KDSP00101/data