apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ckad00017
  labels:
    app: webapp
    tier: dmz
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80