apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.16
      ports:
      - containerPort: 80
      env:
        - name: COOL_VARIABLE
          valueFrom:
            secretKeyRef:
              name: another-secret
              key: key1

    # Additional container to verify the existence of the secret.
    - name: netshoot
      image: nicolaka/netshoot
      tty: true
      stdin: true
      env:
        - name: COOL_VARIABLE
          valueFrom:
            secretKeyRef:
              name: another-secret
              key: key1