apiVersion: batch/v1
kind: Job
metadata:
  name: busybox-job
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox:1.35
        args: ["bin/sh", "-c", "date;", "echo Hello from the Kubernetes cluster"]
      restartPolicy: Never
  activeDeadlineSeconds: 3000
  backoffLimit: 5