# https://github.com/dgkanatsios/CKAD-exercises/blob/main/i.crd.md

# Create a CustomResourceDefinition manifest file for an Operator with the following specifications :
# Name : operators.stable.example.com
# Group : stable.example.com
# Schema: <email: string><name: string><age: integer>
# Scope: Namespaced
# Names: <plural: operators><singular: operator><shortNames: op>
# Kind: Operator

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: operators.stable.example.com
spec:
  group: stable.example.com
  scope: Namespaced
  names:
    plural: operators
    singular: operator
    shortNames:
      - op
    kind: Operator
  versions:
  - name: v1
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              email:
                type: string
              name:
                type: string
              age:
                type: integer
