# https://github.com/dgkanatsios/CKAD-exercises/blob/main/d.configuration.md
# Tips, export to variable
# export ns="-n secret-ops"
# export do="--dry-run=client -o yaml"

# Create a configmap named config with values foo=lala,foo2=lolo
# Display its values
# k create configmap config --from-literal=foo=lala --from-literal=foo2=lolo -o yaml
# k describe configmap config

# Create and display a configmap from a file
# Create the file with
# echo -e "foo3=lili\nfoo4=lele" > config.txt
# echo "foo3=lili`nfoo4=lele" > config.txt # for Windows
# https://stackoverflow.com/questions/36737410/echo-newline-to-powershell-console
# k create configmap config --from-file=config.txt -o yaml
# k describe configmap config

apiVersion: v1
binaryData:
  config.txt: //5mAG8AbwAzAD0AbABpAGwAaQAKAGYAbwBvADQAPQBsAGUAbABlAA0ACgA=
kind: ConfigMap
metadata:
  creationTimestamp: "2025-01-16T13:07:41Z"
  name: config
  namespace: default
  resourceVersion: "27453"
  uid: 817a3c47-03d8-4d11-9ef3-2a29389ce55e

# Create and display a configmap from a .env file
# Create the file with the command
# echo -e "var1=val1\n# this is a comment\n\nvar2=val2\n#anothercomment" > config.env
# echo "var1=val1`n# this is a comment`n`nvar2=val2`n#anothercomment" | Out-File -Encoding "UTF8" config.env # for windows
# k create configmap config --from-env-file=config.env -o yaml

# Create and display a configmap from a file, giving the key 'special'
# Create the file with
# echo -e "var3=val3\nvar4=val4" > config4.txt
# echo "var3=val3`nvar4=val4" > config.txt
# k create cm config --from-file=special=config.txt

# Create a configMap called 'options' with the value var5=val5. Create a new nginx pod that loads the value from variable 'var5' in an env variable called 'option'
# k create cm options --from-literal=var5=val5 -o yaml
# k run options --image=nginx -o yaml --dry-run=client -o yaml > po.yaml

# Create a configMap 'anotherone' with values 'var6=val6', 'var7=val7'. Load this configMap as env variables into a new nginx pod

# Create a configMap 'cmvolume' with values 'var8=val8', 'var9=val9'. Load this as a volume inside an nginx pod on path '/etc/lala'. Create the pod and 'ls' into the '/etc/lala' directory.
