# https://github.com/dgkanatsios/CKAD-exercises/blob/main/d.configuration.md
# Create a secret called mysecret with the values password=mypass
# k create secret generic mysecret --from-literal=password=mypass
# k get secret mysecret -o yaml

# Create a secret called mysecret2 that gets key/value from a file
# Create a file called username with the value admin:
# echo -n admin > username
# k create secret generic mysecret2 --from-file=username

# Get the value of mysecret2
# k get secret mysecret2 -o yaml
# echo -n YWRtaW4= | base64 -d

# Create an nginx pod that mounts the secret mysecret2 in a volume on path /etc/foo
# k run nginx --image=nginx --restart=Never --dry-run=client -o yaml > pod.yaml

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
      - name: mysecret2
        mountPath: /etc/foo
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: mysecret2
      secret:
        secretName: mysecret2
status: {}
