# https://github.com/dgkanatsios/CKAD-exercises/blob/main/d.configuration.md
# Delete the pod you just created and mount the variable 'username' from secret mysecret2 onto a new nginx pod in env variable called 'USERNAME'
# k delete po nginx

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret2
            key: username
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

# k apply -f ./practices/ckad/d.configuration/secrets-2.yaml
# k exec nginx -it -- env
