# https://github.com/dgkanatsios/CKAD-exercises/blob/main/d.configuration.md
# Create a Secret named 'ext-service-secret' in the namespace 'secret-ops'. 
# Then, provide the key-value pair API_KEY=LmLHbYhsgWZwNifiqaRorH8T as literal.
# k create ns secret-ops
# k create secret generic ext-service-secret -n secret-ops --from-literal=API_KEY=LmLHbYhsgWZwNifiqaRorH8T
# k get secret ext-service-secret -o yaml -n secret-ops

# Consuming the Secret. Create a Pod named 'consumer' with the image 'nginx' in the namespace 'secret-ops'and consume the Secret as an environment variable.
# Then, open an interactive shell to the Pod, and print all environment variables.
# k run consumer -n secret-ops --image nginx --restart=Never --dry-run=client -o yaml > pod.yaml

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: consumer
  name: consumer
  namespace: secret-ops
spec:
  containers:
  - image: nginx
    name: consumer
    resources: {}
    env:
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: ext-service-secret
            key: API_KEY
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

# k exec consumer -n secret-ops -- env
