# https://github.com/dgkanatsios/CKAD-exercises/blob/main/d.configuration.md
# See all the service accounts of the cluster in all namespaces
# k get serviceAccount -A

# Create a new serviceaccount called 'myuser'
# k create serviceaccount myuser

# Create an nginx pod that uses 'myuser' as a service account
# k run nginx --image nginx --restart=Never --dry-run=client -o yaml > pod.yaml

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  serviceAccountName: myuser
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

# k apply -f ./practices/ckad/d.configuration/service_accounts.yaml
# k describe po nginx

# Generate an API token for the service account 'myuser'
# k create token myuser
