apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: qutt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.26.0
        resources:
          requests:
            cpu: 300m
            memory: 200Mi
        ports:
        - containerPort: 80