# https://github.com/dgkanatsios/CKAD-exercises/blob/main/c.pod_design.md
# Create a cron job with image busybox that runs every minute and writes 'date; echo Hello from the Kubernetes cluster' to standard output.
# The cron job should be terminated if it takes more than 17 seconds to start execution after its scheduled time (i.e. the job missed its scheduled time).
# kubernetes-certification-practices % k create cj busybox --image busybox --schedule "*/1 * * * *" --dry-run=client -o yaml -- /bin/sh -c 'date; echo Hello from the Kubernetes cluster' > cronjob.yaml

apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: busybox
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: busybox
    spec:
      activeDeadlineSeconds: 17 # 是在 job 而非 cronjob 的層級
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: busybox
            resources: {}
          restartPolicy: OnFailure
  schedule: "*/1 * * * *"
status: {}

# k describe cj busybox
# k get job busybox-28956495
# k describe job busybox-28956495
# k logs busybox-28956495-q4ltf
