# https://github.com/dgkanatsios/CKAD-exercises/blob/main/c.pod_design.md
# Create a cron job with image busybox that runs every minute and writes 'date; echo Hello from the Kubernetes cluster' to standard output.
# The cron job should be terminated if it successfully starts but takes more than 12 seconds to complete execution.

apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: busybox
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: busybox
    spec:
      activeDeadlineSeconds: 12 # 是在 pod 而非 job 或 cronjob 的層級
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: busybox
            resources: {}
          restartPolicy: OnFailure
  schedule: "*/1 * * * *"
status: {}

# Create a job from cronjob.
# k create job busybox --from=cronjob/busybox
