# https://github.com/dgkanatsios/CKAD-exercises/blob/main/c.pod_design.md
# Create a cron job with image busybox that runs every minute and writes 'date; echo Hello from the Kubernetes cluster' to standard output. The cron job should be terminated if it takes more than 17 seconds to start execution after its scheduled time (i.e. the job missed its scheduled time).
# k create cj busybox --image=busybox --restart=Never --dry-run=client -o yaml --schedule="*/1 * * * *" -- /bin/sh -c "date; echo Hello from the Kubernetes cluster" > job.yaml

apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: busybox
spec:
  startingDeadlineSeconds: 17 # 本題重點
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: busybox
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: busybox
            resources: {}
          restartPolicy: Never
  schedule: '*/1 * * * *'
status: {}

# Create a cron job with image busybox that runs every minute and writes 'date; echo Hello from the Kubernetes cluster' to standard output. The cron job should be terminated if it successfully starts but takes more than 12 seconds to complete execution.

# Create a job from cronjob.
