# https://github.com/dgkanatsios/CKAD-exercises/blob/main/c.pod_design.md
# Implement canary deployment by running two instances of nginx marked as version=v1 and version=v2 so that the load is balanced at 75%-25% ratio

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx

# k describe svc # 查服務 ip
# k run busybox --image busybox -it --rm --restart=Never -- wget -O- 10.103.228.137
