# https://github.com/dgkanatsios/CKAD-exercises/blob/main/c.pod_design.md
# Create a job but ensure that it will be automatically terminated by kubernetes if it takes more than 30 seconds to execute
# k create job busybox --image busybox --dry-run=client -o yaml > job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: busybox
spec:
  activeDeadlineSeconds: 30
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
      restartPolicy: Never
status: {}
