# https://github.com/dgkanatsios/CKAD-exercises/blob/main/c.pod_design.md
# Create the same job, make it run 5 times, one after the other. Verify its status and delete it
# k delete job pi

apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: busybox
spec:
  completions: 5
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
      restartPolicy: Never
status: {}

# k get job busybox
