# https://github.com/dgkanatsios/CKAD-exercises/blob/main/c.pod_design.md
# Create a job named pi with image perl:5.34 that runs the command with arguments "perl -Mbignum=bpi -wle 'print bpi(2000)'"
# k create job pi --image=perl:5.34 -- perl -Mbignum=bpi -wle 'print bpi(2000)'

apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: pi
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: perl:5.34
        name: pi
        resources: {}
        args:
        - "-Mbignum=bpi"
        - "-wle 'print bpi(2000)'"
      restartPolicy: Never
status: {}

# Wait till it's done, get the output
# k get po
# k logs pi-sp5vh

# Create a job with the image busybox that executes the command 'echo hello;sleep 30;echo world'
# k create job busybox --image=busybox -- /bin/sh -c "echo hello;sleep 30;echo world;"

# Follow the logs for the pod (you'll wait for 30 seconds)
# k logs busybox-vrtss -f
# -f 是 follow 的意思

# See the status of the job, describe it and see the logs
# k logs job/busybox

# Delete the job
# k delete job busybox

# Create a job but ensure that it will be automatically terminated by kubernetes if it takes more than 30 seconds to execute

# Create the same job, make it run 5 times, one after the other. Verify its status and delete it

# Create the same job, but make it run 5 parallel times
