# https://github.com/dgkanatsios/CKAD-exercises/blob/main/c.pod_design.md
# Create the same job, but make it run 5 parallel times

apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: busybox
spec:
  completions: 5
  parallelism: 5
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
      restartPolicy: Never
status: {}

# k get job busybox
