# https://github.com/dgkanatsios/CKAD-exercises/blob/main/c.pod_design.md
# Create 3 pods with names nginx1,nginx2,nginx3. All of them should have the label app=v1
# k run nginx1 --image=nginx -l=app=v1
# k run nginx2 --image=nginx -l=app=v2
# k run nginx3 --image=nginx -l=app=v3

# Show all labels of the pods
# k get po nginx1 nginx2 nginx3 --show-labels

# Change the labels of pod 'nginx2' to be app=v2
# k label po nginx2 app=v2 --overwrite

# Get the label 'app' for the pods (show a column with APP labels)
# k get po -l app --show-labels

# Get only the 'app=v2' pods
# k get po -l app=v2 --show-labels

# Add a new label tier=web to all pods having 'app=v2' or 'app=v1' labels
# k label po -l "app in(v1,v2)" tier=web # IMPORTANT

# Add an annotation 'owner: marketing' to all pods having 'app=v2' label
# k annotate po -l "app in(v2)" owner=marketing

apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

# Remove the 'app' label from the pods we created before
# k label po nginx1 nginx2 nginx3 app- # IMPORTANT

# Annotate pods nginx1, nginx2, nginx3 with "description='my description'" value
# k annotate po nginx1 nginx2 nginx3 "description=my description" 

# Check the annotations for pod nginx1
# k describe po nginx1 | grep -i "annotations" # For Unix-like
# k describe po nginx1 | Select-String "annotations" # For Windows

# Remove the annotations for these three pods
# k annotate po nginx1 nginx2 nginx3 description- owner-

# Remove these pods to have a clean state in your cluster
# k delete po nginx1 nginx2 nginx3
