# https://github.com/dgkanatsios/CKAD-exercises/blob/main/c.pod_design.md

# Taint a node with key tier and value frontend with the effect NoSchedule. Then, create a pod that tolerates this taint.
# minikube node add # IMPORTANT
# k taint node minikube-m02 tier=frontend:NoSchedule

apiVersion: v1
kind: Pod
metadata:
  name: toleration
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
  tolerations:
  - key: "tier"
    operator: "Equal"
    value: "frontend"
    effect: "NoSchedule"